channels:
    - conda-forge
name: pytraj-gha
dependencies:
    - pyflakes
    - cython=3.2.1
    - numpy=2.2.1
    - parmed
    - pytest
    - mock
    - pytest

    # libcpptraj: bash configure --requires-flink -shared -noarpack --with-bzlib=/opt/conda \
    # --with-zlib=/opt/conda -nosanderlib -nohdf5 --with-netcdf=/opt/conda --with-lapack=/opt/conda \
    # --with-fftw3=/opt/conda
